config/routes.rb
Rails.application.routes.draw do
  resources :income_category do
    resources :incomes
  end
  resources :expense_category do
    resources :expenses
  end
  resources :users do
    resources :accounts
  end
  resources :predicted_incomes
  resources :predicted_expenses
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/accounts/transfer', to: 'accounts#transfer', via: 'get'
  match '/accounts/new_transfer', to: 'accounts#create_transfer', via: 'post'
  match '/visual_incomes', to: 'income_category#visual', via: 'get'
  match '/visual_expenses', to: 'expense_category#visual', via: 'get'

end

app/models/income_category.rb
class IncomeCategory < ActiveRecord::Base
  belongs_to  :user
  has_many    :incomes, dependent: :destroy
  has_many    :predicted_incomes, dependent: :destroy
  validates   :name, presence: true
  validate   :uniqueness_name, on: [:create, :update]

  def uniqueness_name
    categories = IncomeCategory.where(user_id: self.user_id)
    categories.each do |category|
      errors.add(:Название, "уже существует") if self.name == category.name and self.id != category.id
    end
  end
end

app/controllers/income_category_controller.rb
class IncomeCategoryController < ApplicationController

  def index
    @income_categories = IncomeCategory.where(user_id: current_user.id)
    @incomes_array = {}
    @summa = 0
    date = Date.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) if params[:start_date]
    @income_categories.each do |category|
      category.amount = 0
      res = find_by_date(category, date)
      @incomes_array[category.name], @header = res[0], res[1]
      @incomes_array[category.name].each {|income| category.amount += income.value}
      @summa += category.amount
    end
  end

  def show
    @income_category = IncomeCategory.find(params[:id])
    @incomes_array = []
    date = Date.new(params[:start_date][:year].to_i,
                    params[:start_date][:month].to_i,
                    params[:start_date][:day].to_i) if params[:start_date]
    @income_category.amount = 0
    res = find_by_date(@income_category, date)
    @incomes_array, @header = res[0], res[1]
    @incomes_array.each { |income| @income_category.amount += income.value }
  end

  def new
    @income_category = IncomeCategory.new
  end

  def edit
    @income_category = IncomeCategory.find(params[:id])
  end

  def create
    @income_category = IncomeCategory.new(income_category_params)
    @income_category.user_id = current_user.id
    if @income_category.save
      flash[:success] = "Категория #{@income_category.name} создана"
      redirect_to income_category_index_path
    else
      render 'new'
    end
  end

  def update
    @income_category = IncomeCategory.find(params[:id])

    if @income_category.update(income_category_params)
      flash[:success] = "Категория #{@income_category.name} изменена"
      redirect_to income_category_index_path
    else
      render 'edit'
    end
  end

  def destroy
    @income_category = IncomeCategory.find(params[:id])
    @incomes = Income.where(income_category: @income_category.id)
    @incomes.each do |income|
      if income.account_id
        @account = Account.find(income.account_id)
        @account.amount -= income.value
        @account.save
      end
    end
    @income_category.destroy

    flash[:success] = "Категория удалена"
    redirect_to income_category_index_path
  end

  def visual
    @income_categories = IncomeCategory.where(user_id: current_user.id)
    @incomes_array = {}
    @chart = {}
    date = Date.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) if params[:start_date]
    @income_categories.each do |category|
      category.amount = 0
      res = find_by_date(category, date)
      @incomes_array[category.name], @header = res[0], res[1]
      @incomes_array[category.name].each {|income| category.amount += income.value}
      @chart[category.name] = category.amount
    end
  end

  private

    def find_by_date(category, date)
      array = []
      case(params[:period])
      when "1"
        array = Income.where(income_category: category.id,
                                      date: date)
        header = date
      when "2"
        array = Income.where(income_category: category.id,
                                      date: (date.beginning_of_week..date.end_of_week))
        header = date.beginning_of_week.to_s + " - " + date.end_of_week.to_s
      when "3"
        array = Income.where(income_category: category.id,
                                      date: (date.beginning_of_month..date.end_of_month))
        header = date.beginning_of_month.to_s + " - " + date.end_of_month.to_s
      when "4"
        array = Income.where(income_category: category.id,
                                      date: (date.beginning_of_year..date.end_of_year))
        header = date.beginning_of_year.to_s + " - " + date.end_of_year.to_s
      else
        date = Date.today unless params[:start_date]

        array = Income.where(income_category: category.id,
                                        date: date)
        header = date
      end
      res = []
      return res << array << header
    end

    def income_category_params
      params.require(:income_category).permit(:name)
    end

end

app/helpers/income_category_helper.rb
module IncomeCategoryHelper
end

app/views/income_category/_error_message.html.erb
<% if @income_category.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@income_category.errors.count, "error") %>.
    </div>
    <ul>
    <% @income_category.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/income_category/edit.html.erb
<% provide(:title, "Редактирование категории доходов") %>
<h1>Редактирование вашей категории</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for :income_category, url: income_category_path(@income_category),
      method: :patch do |f| %>
      <%= render 'error_message' %>

      <%= f.label :Название %>
      <%= f.text_field :name %>

      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to 'Назад', income_category_index_path %>
  </div>
</div>

app/views/income_category/index.html.erb
<% provide(:title, 'Все доходы') %>
<h1>Список доходов за <%= @header %></h1>

<div class="row">
  <div class="span6 offset3">
    <table cellpadding=5>
      <thead>
        <tr>
          <th>Имя</th>
          <th>Сумма</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      <% @income_categories.each do |category| %>
        <tr>
          <td><strong><%= category.name %></strong></td>
          <td><%= category.amount %></td>
          <td><%= link_to 'Показать', income_category_path(category) %></td>
          <td><%= link_to 'Редактировать', edit_income_category_path(category) %></td>
          <td><%= link_to 'Удалить', income_category_path(category),
            method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
        <% @incomes_array[category.name].each do |income| %>
          <tr>
            <ul>
          <td>

            <li><%= income.description %> - <%= income.value %> - <%= income.date %></li>
            </td>
            <td></td>
            <td><%= link_to 'Показать', "/income_category/#{category.id}/incomes/#{income.id}" %></td>
            <td><%= link_to 'Редактировать', "/income_category/#{category.id}/incomes/#{income.id}/edit" %></td>
            <td><%= link_to 'Удалить', "/income_category/#{category.id}/incomes/#{income.id}",
              method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </ul></tr>
        <% end %>
        <tr>
          <td><ul><%= link_to 'Новый доход',
            new_income_category_income_path(category) %></ul></td>
        </tr>
      <% end %>
      <tr>
        <td><strong>Всего</strong></td>
        <td><strong><%= @summa %></strong></td>
      </tr>
    </tbody>
</table>

  <br>
  <%= link_to 'Новая категория', new_income_category_path %><br><br>

  <%= form_for :income_category, url: income_category_index_path,
    method: :get do |f| %>
    <b>Дата:</b>
    <%= select_date Date.today, prefix: :start_date %>
    <b>Период:</b><br>
    <%= select_tag(:period, options_for_select([['День', 1], ['Неделя', 2], ['Месяц', 3], ['Год', 4]])) %>
    <%= f.submit "Далее" %>
  <% end %>

  <%= link_to 'Назад к аккаунту', user_path(current_user) %>
  </div>
</div>

app/views/income_category/new.html.erb
<% provide(:title, 'Создать новую категорию') %>
<h1>Создать новую категорию</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for :income_category, url: income_category_index_path do |f| %>
      <%= render 'error_message' %>

      <%= f.label :Название %>
      <%= f.text_field :name %>

      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to 'Назад', income_category_index_path %>
  </div>
</div>

app/views/income_category/show.html.erb
<% provide(:title, @income_category.name) %>
<h1><%= @income_category.name %> за <%= @header %></h1>

<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Название:</strong>
      <%= @income_category.name %>
    </p>

    <p>
      <strong>Сумма:</strong>
      <%= @income_category.amount %>
    </p>

    <% @incomes_array.each do |income| %>
      <tr><td><ul>
            <li><%= income.description %> - <%= income.value %> - <%= income.date %></li></td>
             <td><%= link_to 'Показать', "/income_category/#{@income_category.id}/incomes/#{income.id}" %></td>
              <td><%= link_to 'Редактировать', "/income_category/#{@income_category.id}/incomes/#{income.id}/edit" %></td>
              <td><%= link_to 'Удалить', "/income_category/#{@income_category.id}/incomes/#{income.id}",
                method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </ul></tr>
    <% end %>
    <%= link_to 'Новый доход', new_income_category_income_path(@income_category) %>

    <br><br>
      <%= form_for :income_category, url: income_category_path,
        method: :get do |f| %>
        <b>Дата:</b>
        <%= select_date Date.today, prefix: :start_date %>
        <b>Период:</b><br>
        <%= select_tag(:period, options_for_select([['День', 1], ['Неделя', 2], ['Месяц', 3], ['Год', 4]])) %><br><br>
        <%= f.submit "Далее" %>
      <% end %>

    <%= link_to 'Назад', income_category_index_path %>
  </div>
</div>

app/views/income_category/visual.html.erb
<% provide(:title, 'Диаграма доходов') %>
<h1> Диаграма доходов за <%= @header %></h1>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% if @chart.all? {|name, amount| amount == 0} %>
  <h3 align="center">Список доходов за эту дату пуст</h3>
<% else %>
  <%= pie_chart @chart %>
<% end %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for :income_category, url: visual_incomes_path,
      method: :get do |f| %>
      <b>Дата:</b>
      <%= select_date Date.today, prefix: :start_date %>
      <b>Период:</b><br>
      <%= select_tag(:period, options_for_select([['День', 1], ['Неделя', 2], ['Месяц', 3], ['Год', 4]])) %>
      <%= f.submit "Далее" %>
    <% end %>
  </div>
</div>