config/routes.rb
Rails.application.routes.draw do
  resources :income_category do
    resources :incomes
  end
  resources :expense_category do
    resources :expenses
  end
  resources :users do
    resources :accounts
  end
  resources :predicted_incomes
  resources :predicted_expenses
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/accounts/transfer', to: 'accounts#transfer', via: 'get'
  match '/accounts/new_transfer', to: 'accounts#create_transfer', via: 'post'
  match '/visual_incomes', to: 'income_category#visual', via: 'get'
  match '/visual_expenses', to: 'expense_category#visual', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :income_categories, dependent: :destroy
  has_many :accounts, dependent: :destroy

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  after_create :create_categories_and_accounts


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  has_secure_password

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

    def create_categories_and_accounts
      income_category_name = ["Депозит", "Зарплата", "Сбережения"]
      income_category_name.each { |name| IncomeCategory.create(name: name, amount: 0, user_id: self.id) }

      expense_category_name = ["Счета", "Машина", "Одежда", "Телефон", "Продукты", "Рестораны", "Развлечения", "Подарки", "Здоровье", "Дом", "Спорт", "Питомцы", "Такси", "Гигиена", "Транспорт"]
      expense_category_name.each { |name| ExpenseCategory.create(name: name,  amount: 0, user_id: self.id) }

      accounts_name = ["Кошелек", "Карта для оплаты"]
      accounts_name.each { |name| Account.create(name: name, amount: 0, user_id: self.id) }
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user,     only: [:destroy, :index]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  # При построении формы с помощью form_for(@user), Rails использует POST
  # если @user.new_record? это true и PATCH если это является false.

  def edit
  end

  def create
    @user = User.create(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Money Controller!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    #Before filters

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user),
        notice: "Вы не имеете доступа к этой странице" unless current_user?(@user)
    end

    def admin_user
      redirect_to user_path(current_user),
        notice: "Вам нужны права администратора" unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(*parametrs)
    gravatar_id = Digest::MD5::hexdigest(parametrs[0].email.downcase)
    if parametrs[1]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{parametrs[1]}"
    else
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=80"
    end
    image_tag(gravatar_url, alt: parametrs[0].name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :Имя %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :Пароль %>
  <%= f.password_field :password %>

  <%= f.label :Подтверждение_пароля, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>

    <%= gravatar_for @user %>
    <a href="https://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for(user, 52) %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <br><br><br><br><br>
  <ul><h1> Выберите одно из предложеных действий: </h1>
    <li><h4>Просмотр, удаление, редактирование доходов</h4></li>
    <%= link_to 'Доходы', income_category_index_path %>
    <li><h4>Просмотр, удаление, редактирование расходов</h4></li>
    <%= link_to 'Расходы', expense_category_index_path %>
    <li><h4>Просмотр, удаление, редактирование счетов</h4></li>
    <%= link_to 'Счета', user_accounts_path(current_user) %>
    <li><h4>Бюджетирование доходов</h4></li>
    <%= link_to 'Бюджетирование доходов', predicted_incomes_path %>
    <li><h4>Бюджетирование расходов</h4></li>
    <%= link_to 'Бюджетирование расходов', predicted_expenses_path %>
    <li><h4>Диаграма доходов</h4></li>
    <%= link_to 'Диаграма доходов', visual_incomes_path %>
    <li><h4>Диаграма расходов</h4></li>
    <%= link_to 'Диаграма расходов', visual_expenses_path %>
  </ul>
  <br>
</div>