config/routes.rb
Rails.application.routes.draw do
  resources :income_category do
    resources :incomes
  end
  resources :expense_category do
    resources :expenses
  end
  resources :users do
    resources :accounts
  end
  resources :predicted_incomes
  resources :predicted_expenses
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/accounts/transfer', to: 'accounts#transfer', via: 'get'
  match '/accounts/new_transfer', to: 'accounts#create_transfer', via: 'post'
  match '/visual_incomes', to: 'income_category#visual', via: 'get'
  match '/visual_expenses', to: 'expense_category#visual', via: 'get'

end

app/models/expense_category.rb
class ExpenseCategory < ActiveRecord::Base
  belongs_to  :user
  has_many    :expenses, dependent: :destroy
  has_many    :predicted_expenses, dependent: :destroy
  validates   :name, presence: true
  validate    :uniqueness_name, on: [:create, :update]

  def uniqueness_name
    categories = ExpenseCategory.where(user_id: self.user_id)
    categories.each do |category|
      errors.add(:Название, "уже существует") if self.name == category.name and self.id != category.id
    end
  end
end

app/controllers/expense_category_controller.rb
class ExpenseCategoryController < ApplicationController

  def index
    @expense_categories = ExpenseCategory.where(user_id: current_user.id)
    @expenses_array = {}
    @summa = 0
    date = Date.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) if params[:start_date]
    @expense_categories.each do |category|
      category.amount = 0
      res = find_by_date(category, date)
      @expenses_array[category.name], @header = res[0], res[1]
      @expenses_array[category.name].each {|expense| category.amount += expense.value}
      @summa += category.amount
    end
  end

  def show
    @expense_category = ExpenseCategory.find(params[:id])
    @expenses_array = []
    date = Date.new(params[:start_date][:year].to_i,
                    params[:start_date][:month].to_i,
                    params[:start_date][:day].to_i) if params[:start_date]
    @expense_category.amount = 0
    res = find_by_date(@expense_category, date)
    @expenses_array, @header = res[0], res[1]
    @expenses_array.each { |expense| @expense_category.amount += expense.value }
  end

  def new
    @expense_category = ExpenseCategory.new
  end

  def edit
    @expense_category = ExpenseCategory.find(params[:id])
  end

  def create
    @expense_category = ExpenseCategory.new(expense_category_params)
    @expense_category.user_id = current_user.id
    if @expense_category.save
      flash[:success] = "Категория #{@expense_category.name} создана"
      redirect_to expense_category_index_path
    else
      render 'new'
    end
  end

  def update
    @expense_category = ExpenseCategory.find(params[:id])

    if @expense_category.update(expense_category_params)
      flash[:success] = "Категория #{@expense_category.name} изменена"
      redirect_to expense_category_index_path
    else
      render 'edit'
    end
  end

  def destroy
    @expense_category = ExpenseCategory.find(params[:id])
    @expenses = Expense.where(expense_category: @expense_category.id)
    @expenses.each do |expense|
      if expense.account_id
        @account = Account.find(expense.account_id)
        @account.amount += expense.value
        @account.save
      end
    end

    @expense_category.destroy

    flash[:success] = "Категория удалена"
    redirect_to expense_category_index_path
  end

  def visual
    @expense_categories = ExpenseCategory.where(user_id: current_user.id)
    @expenses_array = {}
    @chart = {}
    date = Date.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) if params[:start_date]
    @expense_categories.each do |category|
      category.amount = 0
      res = find_by_date(category, date)
      @expenses_array[category.name], @header = res[0], res[1]
      @expenses_array[category.name].each {|expense| category.amount += expense.value}
      @chart[category.name] = category.amount
    end
  end

  private

    def find_by_date(category, date)
      array = []
      case(params[:period])
      when "1"
        array = Expense.where(expense_category: category.id,
                                      date: date)
        header = date
      when "2"
        array = Expense.where(expense_category: category.id,
                                      date: (date.beginning_of_week..date.end_of_week))
        header = date.beginning_of_week.to_s + " - " + date.end_of_week.to_s
      when "3"
        array = Expense.where(expense_category: category.id,
                                      date: (date.beginning_of_month..date.end_of_month))
        header = date.beginning_of_month.to_s + " - " + date.end_of_month.to_s
      when "4"
        array = Expense.where(expense_category: category.id,
                                      date: (date.beginning_of_year..date.end_of_year))
        header = date.beginning_of_year.to_s + " - " + date.end_of_year.to_s
      else
        date = Date.today unless params[:start_date]

        array = Expense.where(expense_category: category.id,
                                        date: date)
        header = date
      end
      res = []
      return res << array << header
    end

    def expense_category_params
      params.require(:expense_category).permit(:name)
    end

end

app/helpers/expense_categories_helper.rb
module ExpenseCategoriesHelper
end

app/views/expense_category/_error_message.html.erb
<% if @expense_category.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@expense_category.errors.count, "error") %>.
    </div>
    <ul>
    <% @expense_category.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/expense_category/edit.html.erb
<% provide(:title, "Редактирование категории расходов") %>
<h1>Редактирование вашей категории</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for :expense_category, url: expense_category_path(@expense_category),
      method: :patch do |f| %>
      <%= render 'error_message' %>

      <%= f.label :Название %>
      <%= f.text_field :name %>

      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to 'Назад', expense_category_index_path %>
  </div>
</div>

app/views/expense_category/index.html.erb
<% provide(:title, 'все расходы') %>
<h1>Список расходов за <%= @header %></h1>

<div class="row">
  <div class="span6 offset3">
    <table cellpadding=5>
      <thead>
        <tr>
          <th>Имя</th>
          <th>Сумма</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      <% @expense_categories.each do |category| %>
        <tr>
          <td><strong><%= category.name %></strong></td>
          <td><%= category.amount %></td>
          <td><%= link_to 'Показать', expense_category_path(category) %></td>
          <td><%= link_to 'Редактировать', edit_expense_category_path(category) %></td>
          <td><%= link_to 'Удалить', expense_category_path(category),
            method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
        <% @expenses_array[category.name].each do |expense| %>
          <tr>
            <ul>
          <td>

            <li><%= expense.description %> - <%= expense.value %> - <%= expense.date %></li>
            </td>
            <td></td>
            <td><%= link_to 'Показать', "/expense_category/#{category.id}/expenses/#{expense.id}" %></td>
            <td><%= link_to 'Редактировать', "/expense_category/#{category.id}/expenses/#{expense.id}/edit" %></td>
            <td><%= link_to 'Удалить', "/expense_category/#{category.id}/expenses/#{expense.id}",
              method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </ul></tr>
        <% end %>
        <tr>
          <td><ul><%= link_to 'Новый расход',
            new_expense_category_expense_path(category) %></ul></td>
        </tr>
      <% end %>
      <tr>
        <td><strong>Всего</strong></td>
        <td><strong><%= @summa %></strong></td>
      </tr>
    </tbody>
</table>

  <br>
  <%= link_to 'Новая категория', new_expense_category_path %><br><br>

  <%= form_for :expense_category, url: expense_category_index_path,
    method: :get do |f| %>
    <b>Дата:</b>
    <%= select_date Date.today, prefix: :start_date %>
    <b>Период:</b><br>
    <%= select_tag(:period, options_for_select([['День', 1], ['Неделя', 2], ['Месяц', 3], ['Год', 4]])) %>
    <%= f.submit "Далее" %>
  <% end %>

  <%= link_to 'Назад к аккаунту', user_path(current_user) %>
  </div>
</div>

app/views/expense_category/new.html.erb
<% provide(:title, 'Создать новую категорию') %>
<h1>Создать новую категорию</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for :expense_category, url: expense_category_index_path do |f| %>
      <%= render 'error_message' %>

      <%= f.label :Название %>
      <%= f.text_field :name %>

      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to 'Назад', expense_category_index_path %>
  </div>
</div>

app/views/expense_category/show.html.erb
<% provide(:title, @expense_category.name) %>
<h1><%= @expense_category.name %> за <%= @header %></h1>

<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Название:</strong>
      <%= @expense_category.name %>
    </p>

    <p>
      <strong>Сумма:</strong>
      <%= @expense_category.amount %>
    </p>

    <% @expenses_array.each do |expense| %>
      <tr><td><ul>
            <li><%= expense.description %> - <%= expense.value %> - <%= expense.date %></li></td>
             <td><%= link_to 'Показать', "/expense_category/#{@expense_category.id}/expenses/#{expense.id}" %></td>
              <td><%= link_to 'Редактировать', "/expense_category/#{@expense_category.id}/expenses/#{expense.id}/edit" %></td>
              <td><%= link_to 'Удалить', "/expense_category/#{@expense_category.id}/expenses/#{expense.id}",
                method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </ul></tr>
    <% end %>
    <%= link_to 'Новый доход', new_expense_category_expense_path(@expense_category) %>

    <br><br>
      <%= form_for :expense_category, url: expense_category_path,
        method: :get do |f| %>
        <b>Дата:</b>
        <%= select_date Date.today, prefix: :start_date %>
        <b>Период:</b><br>
        <%= select_tag(:period, options_for_select([['День', 1], ['Неделя', 2], ['Месяц', 3], ['Год', 4]])) %><br><br>
        <%= f.submit "Далее" %>
      <% end %>

    <%= link_to 'Назад', expense_category_index_path %>
  </div>
</div>

app/views/expense_category/visual.html.erb
<% provide(:title, 'Диаграма расходов') %>
<h1> Диаграма расходов за <%= @header %></h1>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% if @chart.all? {|name, amount| amount == 0} %>
  <h3 align="center">Список расходов за эту дату пуст</h3>
<% else %>
  <%= pie_chart @chart %>
<% end %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for :expense_category, url: visual_expenses_path,
      method: :get do |f| %>
      <b>Дата:</b>
      <%= select_date Date.today, prefix: :start_date %>
      <b>Период:</b><br>
      <%= select_tag(:period, options_for_select([['День', 1], ['Неделя', 2], ['Месяц', 3], ['Год', 4]])) %>
      <%= f.submit "Далее" %>
    <% end %>
  </div>
</div>