config/routes.rb
Rails.application.routes.draw do
  resources :income_category do
    resources :incomes
  end
  resources :expense_category do
    resources :expenses
  end
  resources :users do
    resources :accounts
  end
  resources :predicted_incomes
  resources :predicted_expenses
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/accounts/transfer', to: 'accounts#transfer', via: 'get'
  match '/accounts/new_transfer', to: 'accounts#create_transfer', via: 'post'
  match '/visual_incomes', to: 'income_category#visual', via: 'get'
  match '/visual_expenses', to: 'expense_category#visual', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Money Controller by Pasha Naumenko
  </small>
  <nav>
    <ul>
      <li><%= link_to "Про нас",   about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
      <li><a href="#">Новости</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "money controller", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Домой",    root_path %></li>
          <li><%= link_to "Помощь",    help_path %></li>
          <% if signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "Пользователи", users_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Выйти", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Войти", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>